name: biller_pro
description: A professional billing and inventory management mobile application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  lucide_icons: 
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.11.1
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default:21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
